// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJGKezjJUxoS2ct86IkIrAUZoQ-HxjMmY',
    appId: '1:186651823366:web:b70dda133033ce7b0fe287',
    messagingSenderId: '186651823366',
    projectId: 'metromanager-8a7cb',
    authDomain: 'metromanager-8a7cb.firebaseapp.com',
    storageBucket: 'metromanager-8a7cb.firebasestorage.app',
    measurementId: 'G-5WTV5NTTP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCYzj2X0Agjfepe5jn9A8BvV7qUNNBlg',
    appId: '1:186651823366:android:b14967a1d131ad550fe287',
    messagingSenderId: '186651823366',
    projectId: 'metromanager-8a7cb',
    storageBucket: 'metromanager-8a7cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq1J81giqZW3bdYF6j_9Jvgje255LaLWs',
    appId: '1:186651823366:ios:50f830ec259454f40fe287',
    messagingSenderId: '186651823366',
    projectId: 'metromanager-8a7cb',
    storageBucket: 'metromanager-8a7cb.firebasestorage.app',
    iosBundleId: 'com.metromanager.metroManager',
  );
}
